trigger:
- main

pool:
  name: 'CloudAgentPool'
  #vmImage: ubuntu-latest

variables:
  serviceConnectionName: 'UtilityProjectConnection'
  resourceGroupName: 'rg-scarredentos-0001'
  location: 'eastus'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(serviceConnectionName)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: 'infra/main.bicep'
    deploymentMode: 'Incremental'